---
teleport_version: "{{ lookup('env', 'Teleport_Version') | default('15.0.0') }}"
teleport_public_name: "{{ lookup('env', 'Teleport_Public_Name') }}"
teleport_public_proxy_hostname: "{{ lookup('env', 'Teleport_Public_Proxy_Hostname') | default(lookup('env', 'Teleport_Public_Name')) }}"
teleport_proxy_server: "{{ (lookup('env', 'Teleport_Public_Proxy_Hostname') or lookup('env', 'Teleport_Public_Name')) + ':443' }}"
teleport_join_token: "{{ lookup('env', 'Teleport_Join_Token') }}"
teleport_data_dir: /var/lib/teleport
teleport_config_dir: /etc/teleport
teleport_app_haos_url: "{{ lookup('env', 'Teleport_App_Haos_URL') | default('haos.shitbox.dev:8123') }}"

